name = "marchmadness"
main = "./worker/index.ts"
compatibility_date = "2025-04-01"

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "BRACKET_KV"
id = "6d28c282ed374b8c889b8030d7651449"
